@tool
# audio_manifest.gd
#
# This script defines the AudioManifest resource, which acts as a lookup table
# for all audio files (SFX and music) used by the CafeAudioManager plugin.
# It maps user-friendly string keys to Godot's unique resource IDs (UIDs),
# ensuring proper audio playback in both editor and exported builds.
# This resource is automatically generated by 'generate_audio_manifest.gd'.
extends Resource
class_name AudioManifest

@export var music_data: Dictionary = {}
@export var sfx_data: Dictionary = {}
